In [2]:
from flask import Flask, request, jsonify, render_template
from ultralytics import YOLO
import cv2, os, re,subprocess
import numpy as np

In [3]:
os.chdir("../")

In [3]:
# Define the function to segment cracks
def segment_cracks(image_path, output_path):
    command = f"python predict.py --config configs/hrsegnetb32.yml --model_path hrsegnetb32/best_model/model.pdparams --image_path {image_path} --save_dir {output_path}"
    subprocess.run(command, shell=True)

In [4]:
filename = "CRACK500_20160222_080933_361_1281_jpg.rf.cf62a2ea07db09d24fddbbf2765e11cb.jpg"

In [5]:
model = YOLO('runs/segment/train2/weights/best.pt')

In [6]:
results = model.predict(source=filename,save=True)


image 1/1 d:\CrackedSegmentationModel\CRACK500_20160222_080933_361_1281_jpg.rf.cf62a2ea07db09d24fddbbf2765e11cb.jpg: 640x640 1 Cracks, 233.5ms
Speed: 8.9ms preprocess, 233.5ms inference, 1542.7ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\segment\predict15


In [7]:
print(results)

[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: ultralytics.engine.results.Masks object
names: {0: 'Cracks'}
obb: None
orig_img: array([[[165, 155, 137],
        [159, 149, 131],
        [152, 142, 124],
        ...,
        [183, 174, 154],
        [182, 173, 153],
        [182, 173, 153]],

       [[165, 155, 137],
        [161, 151, 133],
        [157, 147, 129],
        ...,
        [188, 179, 159],
        [184, 175, 155],
        [180, 171, 151]],

       [[159, 149, 131],
        [159, 149, 131],
        [158, 148, 130],
        ...,
        [195, 186, 166],
        [187, 178, 158],
        [181, 172, 152]],

       ...,

       [[ 96,  88,  71],
        [ 97,  89,  72],
        [100,  92,  75],
        ...,
        [103,  93,  75],
        [ 96,  86,  68],
        [ 94,  84,  66]],

       [[ 90,  82,  65],
        [ 96,  88,  71],
        [105,  97,  80],
        ...,
        [112, 100,  82],
  

In [8]:
image_path = "runs/segment/predict15/CRACK500_20160222_080933_361_1281_jpg.rf.cf62a2ea07db09d24fddbbf2765e11cb.jpg"

# Attempt to read the image
input_image = cv2.imread(image_path)

# Check if the image was read successfully
if input_image is None:
    print("Error: Unable to read the image file.")
else:
    # Get the dimensions of the image
    height, width, _ = input_image.shape
    print("Image dimensions - Height:", height, "Width:", width)


Image dimensions - Height: 640 Width: 640


In [9]:
total_segmented_area = 0

In [10]:
parent_directory = "runs/segment/"
directories = [d for d in os.listdir(parent_directory) if os.path.isdir(os.path.join(parent_directory, d))]
pattern = "predict"
filtered_directories = [d for d in directories if d.startswith(pattern) and d[len(pattern):].isdigit()]
latest_directory = max(filtered_directories, key=lambda x: int(re.search(r'\d+$', x).group()))
image_path = os.path.join(parent_directory, latest_directory, "inputImage.jpg").replace('\\', '/')
image_path

'runs/segment/predict15/inputImage.jpg'

In [12]:
output_dir= 'output/result/gray_scale'
os.makedirs(output_dir, exist_ok=True)
output_dir1= 'output/result/after_dilated'
os.makedirs(output_dir1, exist_ok=True)
#crop_filename = "wall_image.jpg"
# Segment the cracks in the scaled crop
segment_cracks(image_path, 'output/result')

In [4]:
hsv_image = cv2.cvtColor(cv2.imread(f"output/result/pseudo_color_prediction/wall_image.png"), 
                         cv2.COLOR_BGR2HSV)

FileNotFoundError: [Errno 2] No such file or directory: 'output/result/pseudo_color_prediction/wall_image.png'

In [5]:
input_image = cv2.imread(r'runs/segment/predict4/inputImage.jpg')

In [6]:
input_image

array([[[107, 106, 116],
        [101, 103, 111],
        [ 96,  98, 106],
        ...,
        [ 59,  58, 252],
        [ 54,  54, 254],
        [ 54,  58, 255]],

       [[105, 105, 111],
        [101, 101, 107],
        [ 95,  98, 102],
        ...,
        [ 67,  64, 244],
        [ 57,  59, 247],
        [ 56,  59, 251]],

       [[ 98,  98,  98],
        [ 92,  94,  94],
        [ 88,  90,  90],
        ...,
        [ 73,  72, 222],
        [ 64,  66, 231],
        [ 61,  65, 238]],

       ...,

       [[119, 120, 116],
        [122, 123, 119],
        [125, 126, 122],
        ...,
        [128, 124, 123],
        [124, 120, 119],
        [121, 117, 116]],

       [[121, 122, 118],
        [123, 124, 120],
        [124, 125, 121],
        ...,
        [128, 124, 123],
        [124, 120, 119],
        [121, 117, 116]],

       [[123, 124, 120],
        [124, 125, 121],
        [124, 125, 121],
        ...,
        [127, 123, 122],
        [124, 120, 119],
        [121, 117, 116]]

In [7]:
cv2.imshow('Input Image', input_image)
cv2.waitKey(0)  # Wait for any key press
cv2.destroyAllWindows()  # Close all OpenCV windows

In [8]:
height, width, _ = input_image.shape

In [9]:
height

640

In [10]:
width

640

In [11]:
total_segmented_area = 0

In [12]:
def segment_cracks(image_path, output_path):
    command = f"python predict.py --config configs/hrsegnetb32.yml --model_path hrsegnetb32/best_model/model.pdparams --image_path {image_path} --save_dir {output_path}"
    subprocess.run(command, shell=True)

In [13]:
output_dir= 'output/result/gray_scale'
os.makedirs(output_dir, exist_ok=True)
output_dir1= 'output/result/after_dilated'
os.makedirs(output_dir1, exist_ok=True)
crop_filename = "wall_image.jpg"
# Segment the cracks in the scaled crop
segment_cracks(crop_filename, 'output/result')

In [14]:
hsv_image = cv2.cvtColor(cv2.imread(f"runs\segment\predict4\inputImage.jpg"), cv2.COLOR_BGR2HSV)

In [21]:
hsv_image

array([[[177,  22, 116],
        [  6,  23, 111],
        [  6,  24, 106],
        ...,
        [  0, 196, 252],
        [  0, 201, 254],
        [  1, 201, 255]],

       [[  0,  14, 111],
        [  0,  14, 107],
        [ 13,  18, 102],
        ...,
        [179, 188, 244],
        [  0, 196, 247],
        [  0, 198, 251]],

       [[  0,   0,  98],
        [ 30,   5,  94],
        [ 30,   6,  90],
        ...,
        [  0, 172, 222],
        [  0, 184, 231],
        [  1, 190, 238]],

       ...,

       [[ 83,   9, 120],
        [ 83,   8, 123],
        [ 83,   8, 126],
        ...,
        [114,  10, 128],
        [114,  10, 124],
        [114,  11, 121]],

       [[ 83,   8, 122],
        [ 83,   8, 124],
        [ 83,   8, 125],
        ...,
        [114,  10, 128],
        [114,  10, 124],
        [114,  11, 121]],

       [[ 83,   8, 124],
        [ 83,   8, 125],
        [ 83,   8, 125],
        ...,
        [114,  10, 127],
        [114,  10, 124],
        [114,  11, 121]]

In [31]:
# Change it here 
lower_green = np.array([245, -10, -10])  # Lower bound for green color
upper_green = np.array([(265, 10, 10)])  # Upper bound for green color

In [23]:
lower_green

array([35, 50, 50])

In [33]:
upper_green

array([[265,  10,  10]])

In [32]:
mask = cv2.inRange(hsv_image, lower_green, upper_green)
mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [34]:
segmented_image = np.where(mask == 255, 1, 0).astype(np.uint8) * 255
segmented_image

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [35]:
cv2.imwrite(f"{output_dir}/wall_image.jpg", segmented_image)

True

In [37]:
import cv2
import numpy as np

# Load the original image
original_image = cv2.imread("runs/segment/predict4/inputImage.jpg")

# Make sure the image is loaded successfully
if original_image is None:
    print("Error: Unable to load image.")
    exit()

# Convert the image to HSV color space
hsv_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2HSV)

# Define the lower and upper threshold values for green
lower_green = np.array([245, -10, -10])  # Lower bound for green color
upper_green = np.array([(265, 10, 10)])  # Upper bound for green color

# Create the binary mask for the green color range
mask = cv2.inRange(hsv_image, lower_green, upper_green)

# Convert the binary mask to a binary image
segmented_image = np.where(mask == 255, 1, 0).astype(np.uint8) * 255

# Calculate the percentage of green in the original image
total_green_pixels = np.count_nonzero(mask == 255)
total_pixels = np.prod(original_image.shape[:2])
percentage_green = (total_green_pixels / total_pixels) * 100

print("Percentage of green in the original image: {:.2f}%".format(percentage_green))

# Save the segmented image
cv2.imwrite("runs/segment/predict4/segmented_image.jpg", segmented_image)


Percentage of green in the original image: 0.00%


True

In [26]:
import cv2
import numpy as np

# Load the original image
original_image = cv2.imread("runs/segment/predict4/inputImage.jpg")

# Make sure the image is loaded successfully
if original_image is None:
    print("Error: Unable to load image.")
    exit()

# Convert the original image to grayscale
gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)

# Convert the grayscale image to a 3-channel image (for masking)
gray_image_3ch = cv2.cvtColor(gray_image, cv2.COLOR_GRAY2BGR)

# Convert the image to HSV color space
hsv_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2HSV)

# Define the lower and upper threshold values for green
lower_green = np.array([30, 50, 50])
upper_green = np.array([90, 255, 255])

# Create the binary mask for the green color range
mask = cv2.inRange(hsv_image, lower_green, upper_green)

# Highlight the masked region in the grayscale image
highlighted_image = cv2.bitwise_and(gray_image_3ch, gray_image_3ch, mask=mask)

# Display the original grayscale image and the highlighted region
cv2.imshow("Grayscale Image", gray_image)
cv2.imshow("Highlighted Region", highlighted_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [28]:
import cv2
import numpy as np

# Load the original image
original_image = cv2.imread("runs/segment/predict4/inputImage.jpg")

# Make sure the image is loaded successfully
if original_image is None:
    print("Error: Unable to load image.")
    exit()

# Convert the original image to grayscale
gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)

# Convert the grayscale image to a 3-channel image (for masking)
gray_image_3ch = cv2.cvtColor(gray_image, cv2.COLOR_GRAY2BGR)

# Convert the image to HSV color space
hsv_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2HSV)

# Define the lower and upper threshold values for crack (if known)
lower_crack = np.array([0, 0, 0])  # Adjust as needed
upper_crack = np.array([180, 255, 50])  # Adjust as needed

# Create the binary mask for the crack region
mask = cv2.inRange(hsv_image, lower_crack, upper_crack)

# Highlight the crack region in the grayscale image
highlighted_image = cv2.bitwise_and(gray_image_3ch, gray_image_3ch, mask=mask)

# Calculate the total number of pixels in the grayscale image
total_pixels = gray_image.size

# Calculate the number of pixels in the highlighted crack region
crack_pixels = np.count_nonzero(mask)

# Calculate the percentage of crack from the whole image
percentage_crack = (crack_pixels / total_pixels) * 100

print("Percentage of crack in the whole image: {:.2f}%".format(percentage_crack))

# Display the original grayscale image and the highlighted crack region
cv2.imshow("Grayscale Image", gray_image)
#cv2.imshow("Highlighted Crack Region", highlighted_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


Percentage of crack in the whole image: 0.00%


In [30]:
import cv2
import numpy as np

# Load the original image
original_image = cv2.imread("runs/segment/predict4/inputImage.jpg")

# Make sure the image is loaded successfully
if original_image is None:
    print("Error: Unable to load image.")
    exit()

# Convert the original image to grayscale
gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)

# Convert the image to HSV color space
hsv_image = cv2.cvtColor(gray_image, cv2.COLOR_BGR2HSV)

# Define the lower and upper threshold values for crack (if known)
lower_crack = np.array([0, 0, 0])  # Adjust as needed
upper_crack = np.array([180, 255, 50])  # Adjust as needed

# Create the binary mask for the crack region
mask = cv2.inRange(hsv_image, lower_crack, upper_crack)

# Highlight the crack region in the grayscale image
highlighted_crack = cv2.bitwise_and(gray_image, gray_image, mask=mask)

# Convert the highlighted crack region to white and the rest to black
highlighted_crack_binary = np.where(highlighted_crack > 0, 255, 0).astype(np.uint8)

# Display the original image and the highlighted crack region
cv2.imshow("Original Image", original_image)
cv2.imshow("Highlighted Cracks", highlighted_crack_binary)
cv2.waitKey(0)
cv2.destroyAllWindows()


error: OpenCV(4.9.0) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0x806cd31c::Set<3,-1,-1>,struct cv::impl::A0x806cd31c::Set<0,5,-1>,4>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1
